### ISSUE TITLE
[Discussion] Test Scenario Runners

### ISSUE THREAD

**Issue by bigs** [libp2p/testlab#2]
# Test Scenario Runners
_Scenarios encode behavior of nodes in the test network. These scenarios are analyzed via metrics output. How should they work?_

## Overview
At present, topologies are defined using a pretty simple [JSON file](https://github.com/libp2p/testlab/blob/541a6d8c4b62e820f7f358191f2961e017dad218/examples/test.json). I'd like to extend these with a plugin for test scenarios. Scenarios control daemons via the control protocol, creating simulated work loads that we can then analyze via grafana, etc.

## General implementation guidelines
There are two major pieces to this work.

### Scenario Plugin
The testlab will have to be extended with a new plugin type that executes scenarios and populates their runtime environment with necessary information to discover the daemon network. This plugin will have to have a standardized environment that all scenarios can depend on to exist. It should probably include access to consul for service discovery and some sort of scoping to limit it to a subset of peers tagged with metadata.

### Scenario Framework
Golang library that leverages the scenario plugin environment to power these scenarios. Open questions:

- How many scenario runners per peer?
- What does an ergonomic DSL for encoding node behaviors look like?
- Should scenario runners use consul to synchronize over certain tasks i.e. common keys to put/get from DHT?

**Comment by yusefnapora** [comment]
Could we use Consul's [service segmentation](https://www.consul.io/docs/connect/intentions.html) to simulate network partitions? It would be nice when testing e.g. circuit relay to know that two nodes can't communicate directly and have that enforced by the test setup.

**Comment by anacrolix** [comment]
YAML might be better suited, particularly for embedding snippets of stuff for other languages (bash etc.), keys, parts of scenarios etc., and the fact that humans will be writing these?

As a potential writer of scenarios I'd expect to be able to describe:
```yaml
global_config:
  # some stuff like run name, permissions, consul and coordinator service configurations etc.
nodes:
  - num: 50
     network: &nat # some nat nonsense
     steps:
       - &install |
         go get dht
         some_other_install
       - |
         generate_data
         run_dht
     metrics: # how to generate metrics
  - num: 500
    <<: *nat # run the same nat as the above guys
    steps:
      - *install
      - |
        run_dht_to_get_data
    metrics:
```

Probably some synchronization will be necessary so nodes are in expected states before certain steps run. Some variance between nodes might be necessary, for example exposing an instance ID as an environment variable or something so instances can deterministically generate random data/keys/peer IDs etc.

Is this the kind of input you're after?
